//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geronimus.UnitTests {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class TestSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static TestSettings defaultInstance = ((TestSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TestSettings())));
        
        public static TestSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Resources\\InitialMatrix.txt")]
        public string InitialMatrixPath {
            get {
                return ((string)(this["InitialMatrixPath"]));
            }
            set {
                this["InitialMatrixPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Resources\\WaitingTimeMatrix.txt")]
        public string WaitingTimeMatrix {
            get {
                return ((string)(this["WaitingTimeMatrix"]));
            }
            set {
                this["WaitingTimeMatrix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Resources\\ExpectedShortestPaths.txt")]
        public string ShortestPathsMatrix {
            get {
                return ((string)(this["ShortestPathsMatrix"]));
            }
            set {
                this["ShortestPathsMatrix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Resources\\PassengerFlow.txt")]
        public string PassengerFlow {
            get {
                return ((string)(this["PassengerFlow"]));
            }
            set {
                this["PassengerFlow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Resources\\ExpectedInitialMatrix.txt")]
        public string ExpectedInitialMatrix {
            get {
                return ((string)(this["ExpectedInitialMatrix"]));
            }
            set {
                this["ExpectedInitialMatrix"] = value;
            }
        }
    }
}
